package com.citymemory.data.local.seed

import com.citymemory.data.local.entities.CityEntity

/**
 * The one city this build ships, and where to find its catalog.
 *
 * The places themselves used to be here, as generated Kotlin. They are now in
 * `assets/mumbai-places.tsv`, read by [PlaceCatalogCodec] — see that file for
 * why. What is left is the city row and the asset name, which are small, stable
 * and hand-written.
 *
 * The catalog is every place OpenStreetMap has mapped inside Mumbai's postal
 * boundary: nothing is curated away, chains included, because the app lets you
 * add a place it is missing and the less often that is necessary the better.
 * `tools/curated.tsv` still exists and still ranks the places a person chose to
 * the top of their category; it no longer decides who is in.
 */
object MumbaiSeed {

    const val CITY_ID = "mumbai"

    /**
     * The catalog asset, generated by `tools/build_seed.py`.
     *
     * The map asset has to be rebuilt whenever this changes —
     * `tools/extract_osm.py` keeps building and footpath geometry only near a
     * catalogued place, and `CityMapAssetTest` fails if a place ends up outside
     * it.
     */
    const val CATALOG_ASSET = "mumbai-places.tsv"

    val city = CityEntity(
        id = CITY_ID,
        name = "Mumbai",
        country = "India",
    )
}
